<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="true" />
<meta name="allow-skip" content="true" />

<title>Warming Stripes: A Problem solving task in R</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-introduction" class="section level2">
<h2>Introduction</h2>
<p>One of the most famous visualisations of recent times not only came from ggplot2*, but also from the University of Reading itself!</p>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/20181204_Warming_stripes_%28global%2C_WMO%2C_1850-2018%29_-_Climate_Lab_Book_%28Ed_Hawkins%29.png/2560px-20181204_Warming_stripes_%28global%2C_WMO%2C_1850-2018%29_-_Climate_Lab_Book_%28Ed_Hawkins%29.png" id="section-id" class="class" style="width:70.0%" /></p>
<p>Professor Ed Hawkin’s ‘Warming Stripes’ graph sparked huge amounts of interest, and debate, thanks to it’s innovative and striking yet easily understood presentation. You can’t go far on the University of Reading campus without seeing it plastered on a poster, sign or even face-mask.</p>
<p>If you aren’t familiar with this plot, then you probably haven’t been at Reading for very long, but you can read more about it here:</p>
<p><a href="https://en.wikipedia.org/wiki/Warming_stripes" class="uri">https://en.wikipedia.org/wiki/Warming_stripes</a></p>
<p><a href="https://showyourstripes.info/" class="uri">https://showyourstripes.info/</a></p>
<p>*(Minor side point: I believe (but may be wrong) that he used the Python implementation of ggplot2. Happy to be corrected if wrong! But the R version is better!)</p>
<p>It is possible to make these plots for ourselves in R, with almost identical formatting to the famous style, using only the skills we have learnt for importing data, and using <code>dplyr</code> &amp; <code>ggplot</code>. But it will require some careful thinking and problem solving to get to that point!</p>
<p>This is the solution page! If you would like to attempt this problem yourself first, please download the files from here:</p>
<p>And there is also a video talking through this solution here:</p>
<p><img src="https://youtu.be/y3UW8gr4lXU" /></p>
</div>
<div id="section-data-methodology" class="section level2">
<h2>Data &amp; Methodology</h2>
<p>We are going to use data from a weather station in Oxford, one of the longest running weather stations for which the data is easily available from the UK Met Service.</p>
<p>The warming stripes show us each ‘stripe’ represent one years data. The colour represents the difference between the yearly average temperature and the average temperature in the reference period, 1971-2000. This is known as the temperature anomaly. We would only want to include years where we have complete data available - given the seasonality of temperatures missing values will certainly lead to biased yearly averages.</p>
<p>Within the plot increasingly dark shades of red represent values with an increasingly positive temperature anomaly; increasingly dark shades of blue represent an increasingly negative temperature anomaly. An anomaly of 0, or close to 0, should be shaded in white, so that the colour scale is symmetrical. When trying to think how it should look visually, take a look at examples of this plot from <a href="https://showyourstripes.info/" class="uri">https://showyourstripes.info/</a> to think about what stylistic changes made be needed to the defaults within ggplot2.</p>
</div>
<div id="section-stage-0-load-libraries" class="section level2">
<h2>Stage 0: Load libraries</h2>
<p>We need these <code>dplyr</code> and <code>ggplot2</code>. So let’s load them in!</p>
<pre class="r"><code>library(dplyr)
library(ggplot2)</code></pre>
</div>
<div id="section-stage-1-import-data" class="section level2">
<h2>Stage 1: Import Data</h2>
<p>We can import the data in a fairly standard way, using read.csv, or the “import dataset” menus</p>
<pre class="r"><code>oxford_data&lt;-read.csv(&quot;oxford_data.csv&quot;)</code></pre>
<p>But if we check the data we notice that there is a problem with one of the columns.</p>
<pre class="r"><code>summary(oxford_data)</code></pre>
<pre><code>##       yyyy            mm              tmax           tmin          
##  Min.   :1853   Min.   : 1.000   Min.   :-0.20   Length:2011       
##  1st Qu.:1894   1st Qu.: 3.000   1st Qu.: 9.00   Class :character  
##  Median :1936   Median : 6.000   Median :13.80   Mode  :character  
##  Mean   :1936   Mean   : 6.491   Mean   :13.95                     
##  3rd Qu.:1978   3rd Qu.: 9.000   3rd Qu.:19.00                     
##  Max.   :2020   Max.   :12.000   Max.   :27.40                     
##       rain       
##  Min.   :  0.50  
##  1st Qu.: 31.45  
##  Median : 49.70  
##  Mean   : 54.70  
##  3rd Qu.: 74.75  
##  Max.   :192.90</code></pre>
<p>We can try and find exactly whats gone wrong by looking at the data file, or looking just at the column that is causing problems.</p>
<pre class="r"><code>oxford_data$tmin</code></pre>
<pre><code>##    [1] &quot;2.7&quot;  &quot;-1.8&quot; &quot;-0.6&quot; &quot;4.5&quot;  &quot;6.1&quot;  &quot;10.7&quot; &quot;12.2&quot; &quot;10.8&quot; &quot;8.4&quot;  &quot;7.4&quot; 
##   [11] &quot;2.3&quot;  &quot;-1.3&quot; &quot;1.5&quot;  &quot;0.6&quot;  &quot;2.2&quot;  &quot;3.5&quot;  &quot;5.7&quot;  &quot;9.7&quot;  &quot;11.6&quot; &quot;10.7&quot;
##   [21] &quot;8.4&quot;  &quot;5.6&quot;  &quot;2&quot;    &quot;2.1&quot;  &quot;-0.4&quot; &quot;-4.5&quot; &quot;0.1&quot;  &quot;2.7&quot;  &quot;4.9&quot;  &quot;9.3&quot; 
##   [31] &quot;13.4&quot; &quot;12.2&quot; &quot;10.4&quot; &quot;8.2&quot;  &quot;3.4&quot;  &quot;-0.1&quot; &quot;2&quot;    &quot;3&quot;    &quot;0.6&quot;  &quot;4.1&quot; 
##   [41] &quot;5.7&quot;  &quot;9.5&quot;  &quot;11.3&quot; &quot;12.5&quot; &quot;8.5&quot;  &quot;6.9&quot;  &quot;2.3&quot;  &quot;1.4&quot;  &quot;-0.6&quot; &quot;0.4&quot; 
##   [51] &quot;1.8&quot;  &quot;3.7&quot;  &quot;6.3&quot;  &quot;10.6&quot; &quot;12.7&quot; &quot;13.2&quot; &quot;11.2&quot; &quot;7.8&quot;  &quot;4.5&quot;  &quot;4.5&quot; 
##   [61] &quot;-0.1&quot; &quot;-1.2&quot; &quot;1.1&quot;  &quot;4&quot;    &quot;6.2&quot;  &quot;11.9&quot; &quot;10.6&quot; &quot;11.3&quot; &quot;11.2&quot; &quot;6.9&quot; 
##   [71] &quot;0.8&quot;  &quot;2.4&quot;  &quot;1.8&quot;  &quot;2.7&quot;  &quot;4.7&quot;  &quot;3.5&quot;  &quot;6.7&quot;  &quot;11.1&quot; &quot;13.7&quot; &quot;12.5&quot;
##   [81] &quot;9.4&quot;  &quot;6.6&quot;  &quot;1.5&quot;  &quot;-1.1&quot; &quot;0.8&quot;  &quot;-1.6&quot; &quot;1.9&quot;  &quot;1.7&quot;  &quot;7.7&quot;  &quot;9.5&quot; 
##   [91] &quot;10.3&quot; &quot;10.9&quot; &quot;7&quot;    &quot;7.3&quot;  &quot;2.1&quot;  &quot;---&quot;  &quot;-0.7&quot; &quot;3.1&quot;  &quot;3.4&quot;  &quot;3&quot;   
##  [101] &quot;6.5&quot;  &quot;11.2&quot; &quot;12&quot;   &quot;12.7&quot; &quot;9.9&quot;  &quot;9.5&quot;  &quot;1.6&quot;  &quot;1.5&quot;  &quot;2.2&quot;  &quot;3.4&quot; 
##  [111] &quot;3.9&quot;  &quot;6.2&quot;  &quot;9.2&quot;  &quot;9.6&quot;  &quot;10.6&quot; &quot;10.5&quot; &quot;9.9&quot;  &quot;7.6&quot;  &quot;0.4&quot;  &quot;3.8&quot; 
##  [121] &quot;2.5&quot;  &quot;2.7&quot;  &quot;1.9&quot;  &quot;4.7&quot;  &quot;6&quot;    &quot;9.6&quot;  &quot;9.5&quot;  &quot;11.9&quot; &quot;7.6&quot;  &quot;7&quot;   
##  [131] &quot;4.6&quot;  &quot;3.3&quot;  &quot;-0.2&quot; &quot;0&quot;    &quot;1.4&quot;  &quot;4.3&quot;  &quot;7.9&quot;  &quot;9.8&quot;  &quot;10.3&quot; &quot;8.8&quot; 
##  [141] &quot;9.4&quot;  &quot;6.8&quot;  &quot;2&quot;    &quot;1.3&quot;  &quot;-0.9&quot; &quot;0.2&quot;  &quot;-0.2&quot; &quot;5.4&quot;  &quot;8.1&quot;  &quot;10.8&quot;
##  [151] &quot;12.5&quot; &quot;10.8&quot; &quot;10.9&quot; &quot;6.1&quot;  &quot;4&quot;    &quot;3.4&quot;  &quot;3.4&quot;  &quot;1.3&quot;  &quot;1.8&quot;  &quot;4.7&quot; 
##  [161] &quot;4.8&quot;  &quot;11.1&quot; &quot;11.2&quot; &quot;11.3&quot; &quot;10.3&quot; &quot;8&quot;    &quot;3.7&quot;  &quot;3.3&quot;  &quot;-1.1&quot; &quot;4.4&quot; 
##  [171] &quot;0.5&quot;  &quot;6.6&quot;  &quot;6.8&quot;  &quot;9.6&quot;  &quot;10.5&quot; &quot;11.8&quot; &quot;9.6&quot;  &quot;6.3&quot;  &quot;1.6&quot;  &quot;0.1&quot; 
##  [181] &quot;1.7&quot;  &quot;3.3&quot;  &quot;2.9&quot;  &quot;4.6&quot;  &quot;7.8&quot;  &quot;9.4&quot;  &quot;12.7&quot; &quot;12.5&quot; &quot;9.4&quot;  &quot;5&quot;   
##  [191] &quot;2.6&quot;  &quot;5.2&quot;  &quot;3&quot;    &quot;5.1&quot;  &quot;1.1&quot;  &quot;6&quot;    &quot;6.5&quot;  &quot;8.8&quot;  &quot;12.4&quot; &quot;10.7&quot;
##  [201] &quot;11.3&quot; &quot;6.1&quot;  &quot;3.2&quot;  &quot;1&quot;    &quot;1.3&quot;  &quot;0.8&quot;  &quot;1.5&quot;  &quot;3.7&quot;  &quot;6.3&quot;  &quot;11.2&quot;
##  [211] &quot;13&quot;   &quot;10.6&quot; &quot;8.2&quot;  &quot;6.7&quot;  &quot;2.1&quot;  &quot;-2.3&quot; &quot;-1.2&quot; &quot;3.8&quot;  &quot;3.2&quot;  &quot;5.3&quot; 
##  [221] &quot;5.8&quot;  &quot;9&quot;    &quot;11.9&quot; &quot;12&quot;   &quot;9.6&quot;  &quot;6&quot;    &quot;0.2&quot;  &quot;0.9&quot;  &quot;2.6&quot;  &quot;4.7&quot; 
##  [231] &quot;3.6&quot;  &quot;4.5&quot;  &quot;5.9&quot;  &quot;10.2&quot; &quot;12.9&quot; &quot;11.3&quot; &quot;10&quot;   &quot;5.2&quot;  &quot;4.6&quot;  &quot;3.5&quot; 
##  [241] &quot;3.2&quot;  &quot;-0.1&quot; &quot;2.2&quot;  &quot;3.9&quot;  &quot;5.4&quot;  &quot;10.3&quot; &quot;11.8&quot; &quot;12.6&quot; &quot;7.8&quot;  &quot;4.7&quot; 
##  [251] &quot;3.8&quot;  &quot;2.1&quot;  &quot;3&quot;    &quot;1&quot;    &quot;3.1&quot;  &quot;5.4&quot;  &quot;6&quot;    &quot;9&quot;    &quot;11.8&quot; &quot;11.2&quot;
##  [261] &quot;10.4&quot; &quot;7.8&quot;  &quot;2.5&quot;  &quot;-2.3&quot; &quot;4.9&quot;  &quot;-0.4&quot; &quot;2.4&quot;  &quot;3.5&quot;  &quot;7.8&quot;  &quot;10.5&quot;
##  [271] &quot;11.1&quot; &quot;12.8&quot; &quot;11.4&quot; &quot;6.4&quot;  &quot;3.6&quot;  &quot;2.4&quot;  &quot;0.6&quot;  &quot;3&quot;    &quot;1.9&quot;  &quot;4.8&quot; 
##  [281] &quot;4.7&quot;  &quot;10&quot;   &quot;13.1&quot; &quot;11.9&quot; &quot;9.8&quot;  &quot;8.8&quot;  &quot;4.1&quot;  &quot;4.9&quot;  &quot;3.2&quot;  &quot;4&quot;   
##  [291] &quot;2.2&quot;  &quot;4.3&quot;  &quot;5.5&quot;  &quot;10.5&quot; &quot;11.1&quot; &quot;11.9&quot; &quot;7.6&quot;  &quot;5.2&quot;  &quot;4.3&quot;  &quot;2.3&quot; 
##  [301] &quot;2.6&quot;  &quot;4.2&quot;  &quot;2.2&quot;  &quot;5.5&quot;  &quot;8.4&quot;  &quot;11.1&quot; &quot;12.6&quot; &quot;13.1&quot; &quot;9.4&quot;  &quot;7.4&quot; 
##  [311] &quot;2.6&quot;  &quot;-2&quot;   &quot;-2.8&quot; &quot;1.1&quot;  &quot;1.1&quot;  &quot;2.4&quot;  &quot;5.2&quot;  &quot;10.2&quot; &quot;11.4&quot; &quot;11.8&quot;
##  [321] &quot;9.5&quot;  &quot;6&quot;    &quot;0.9&quot;  &quot;-3.2&quot; &quot;-2.5&quot; &quot;2.4&quot;  &quot;2.5&quot;  &quot;4.7&quot;  &quot;6.4&quot;  &quot;10&quot;  
##  [331] &quot;12.2&quot; &quot;13.2&quot; &quot;11.5&quot; &quot;4.9&quot;  &quot;3.1&quot;  &quot;3.6&quot;  &quot;-4&quot;   &quot;1.5&quot;  &quot;2.1&quot;  &quot;3.1&quot; 
##  [341] &quot;6.9&quot;  &quot;10.3&quot; &quot;12.5&quot; &quot;10.8&quot; &quot;9.5&quot;  &quot;4.2&quot;  &quot;6.9&quot;  &quot;2.1&quot;  &quot;2.8&quot;  &quot;3.5&quot; 
##  [351] &quot;4&quot;    &quot;5.1&quot;  &quot;7.3&quot;  &quot;9.7&quot;  &quot;11.9&quot; &quot;11.5&quot; &quot;8.3&quot;  &quot;7.2&quot;  &quot;3.5&quot;  &quot;2.5&quot; 
##  [361] &quot;3.3&quot;  &quot;4&quot;    &quot;-1.2&quot; &quot;4.5&quot;  &quot;7.1&quot;  &quot;10.1&quot; &quot;11.2&quot; &quot;11.8&quot; &quot;10.4&quot; &quot;7.4&quot; 
##  [371] &quot;3.3&quot;  &quot;2.7&quot;  &quot;5.1&quot;  &quot;3.1&quot;  &quot;3&quot;    &quot;3.1&quot;  &quot;6.6&quot;  &quot;9.9&quot;  &quot;12.4&quot; &quot;12&quot;  
##  [381] &quot;10.9&quot; &quot;6.1&quot;  &quot;2.6&quot;  &quot;2.9&quot;  &quot;0.9&quot;  &quot;3.8&quot;  &quot;1.2&quot;  &quot;3.6&quot;  &quot;5.3&quot;  &quot;9.8&quot; 
##  [391] &quot;11.9&quot; &quot;9.9&quot;  &quot;8.6&quot;  &quot;4.8&quot;  &quot;4&quot;    &quot;1.3&quot;  &quot;-0.5&quot; &quot;-1.1&quot; &quot;1.5&quot;  &quot;3.8&quot; 
##  [401] &quot;7&quot;    &quot;9.5&quot;  &quot;12&quot;   &quot;12&quot;   &quot;10.3&quot; &quot;8.7&quot;  &quot;3.8&quot;  &quot;-0.3&quot; &quot;-0.5&quot; &quot;0.5&quot; 
##  [411] &quot;-0.1&quot; &quot;1.9&quot;  &quot;6.1&quot;  &quot;10.2&quot; &quot;12.4&quot; &quot;10.5&quot; &quot;8.1&quot;  &quot;3.5&quot;  &quot;2.2&quot;  &quot;0.3&quot; 
##  [421] &quot;0.7&quot;  &quot;-0.7&quot; &quot;0.9&quot;  &quot;3&quot;    &quot;6.3&quot;  &quot;9.6&quot;  &quot;10.9&quot; &quot;10.5&quot; &quot;8.8&quot;  &quot;3.7&quot; 
##  [431] &quot;6&quot;    &quot;2.5&quot;  &quot;-0.1&quot; &quot;-0.4&quot; &quot;1.4&quot;  &quot;3.8&quot;  &quot;8.9&quot;  &quot;10.9&quot; &quot;11.3&quot; &quot;10.8&quot;
##  [441] &quot;9.1&quot;  &quot;5.4&quot;  &quot;4.3&quot;  &quot;0.1&quot;  &quot;3.3&quot;  &quot;0.3&quot;  &quot;2.6&quot;  &quot;3&quot;    &quot;6.6&quot;  &quot;9.7&quot; 
##  [451] &quot;11.2&quot; &quot;10.8&quot; &quot;9.9&quot;  &quot;5.7&quot;  &quot;3&quot;    &quot;-4&quot;   &quot;-1.9&quot; &quot;-0.2&quot; &quot;0.9&quot;  &quot;2.2&quot; 
##  [461] &quot;5.6&quot;  &quot;10.4&quot; &quot;10.7&quot; &quot;10.9&quot; &quot;9.8&quot;  &quot;6.6&quot;  &quot;3.2&quot;  &quot;1.6&quot;  &quot;-0.3&quot; &quot;0.9&quot; 
##  [471] &quot;-0.9&quot; &quot;1.7&quot;  &quot;6.9&quot;  &quot;8.7&quot;  &quot;10.3&quot; &quot;11.5&quot; &quot;8.9&quot;  &quot;4&quot;    &quot;3.8&quot;  &quot;-0.6&quot;
##  [481] &quot;-0.3&quot; &quot;2.5&quot;  &quot;1.7&quot;  &quot;3.9&quot;  &quot;7.7&quot;  &quot;10.2&quot; &quot;12.5&quot; &quot;13&quot;   &quot;8.9&quot;  &quot;6.6&quot; 
##  [491] &quot;1.7&quot;  &quot;1.3&quot;  &quot;1.2&quot;  &quot;2.2&quot;  &quot;2.2&quot;  &quot;5.1&quot;  &quot;5.3&quot;  &quot;9.9&quot;  &quot;12&quot;   &quot;11&quot;  
##  [501] &quot;8.3&quot;  &quot;6.9&quot;  &quot;5.4&quot;  &quot;2.8&quot;  &quot;-1.8&quot; &quot;-5.3&quot; &quot;2&quot;    &quot;5&quot;    &quot;7.3&quot;  &quot;9.8&quot; 
##  [511] &quot;12.2&quot; &quot;12.1&quot; &quot;9.9&quot;  &quot;3.9&quot;  &quot;5.4&quot;  &quot;1.9&quot;  &quot;2.4&quot;  &quot;1.4&quot;  &quot;4.3&quot;  &quot;5.4&quot; 
##  [521] &quot;6.6&quot;  &quot;12&quot;   &quot;12.1&quot; &quot;10.6&quot; &quot;10.7&quot; &quot;4.5&quot;  &quot;1.6&quot;  &quot;1.7&quot;  &quot;-0.2&quot; &quot;4.1&quot; 
##  [531] &quot;4.1&quot;  &quot;4.1&quot;  &quot;5.7&quot;  &quot;11.2&quot; &quot;12.3&quot; &quot;12.1&quot; &quot;8.9&quot;  &quot;6.3&quot;  &quot;4.3&quot;  &quot;1.9&quot; 
##  [541] &quot;4.2&quot;  &quot;2&quot;    &quot;0.6&quot;  &quot;3.7&quot;  &quot;6.8&quot;  &quot;9.5&quot;  &quot;11.1&quot; &quot;12.5&quot; &quot;10&quot;   &quot;8.4&quot; 
##  [551] &quot;4.7&quot;  &quot;5.1&quot;  &quot;2.9&quot;  &quot;2.1&quot;  &quot;0.4&quot;  &quot;5.1&quot;  &quot;6.2&quot;  &quot;10.3&quot; &quot;13.3&quot; &quot;12.3&quot;
##  [561] &quot;10.3&quot; &quot;4.7&quot;  &quot;5.4&quot;  &quot;-0.2&quot; &quot;2.1&quot;  &quot;0.7&quot;  &quot;0.9&quot;  &quot;3.8&quot;  &quot;6.3&quot;  &quot;10.6&quot;
##  [571] &quot;13.4&quot; &quot;11.5&quot; &quot;9.2&quot;  &quot;6.7&quot;  &quot;5.4&quot;  &quot;5&quot;    &quot;1&quot;    &quot;0.1&quot;  &quot;1.2&quot;  &quot;4.3&quot; 
##  [581] &quot;6.2&quot;  &quot;9.4&quot;  &quot;13.2&quot; &quot;11.5&quot; &quot;10&quot;   &quot;6.2&quot;  &quot;1.7&quot;  &quot;0.9&quot;  &quot;2.6&quot;  &quot;-0.5&quot;
##  [591] &quot;3.8&quot;  &quot;3.5&quot;  &quot;5.4&quot;  &quot;9.8&quot;  &quot;11&quot;   &quot;11.1&quot; &quot;8.5&quot;  &quot;6.8&quot;  &quot;4.5&quot;  &quot;2.5&quot; 
##  [601] &quot;2.4&quot;  &quot;4.5&quot;  &quot;4.3&quot;  &quot;2.6&quot;  &quot;7.2&quot;  &quot;8.9&quot;  &quot;11.9&quot; &quot;10.9&quot; &quot;9.7&quot;  &quot;8.5&quot; 
##  [611] &quot;3.9&quot;  &quot;1.6&quot;  &quot;1.4&quot;  &quot;1.5&quot;  &quot;1.6&quot;  &quot;5.4&quot;  &quot;7.4&quot;  &quot;9.2&quot;  &quot;13&quot;   &quot;11&quot;  
##  [621] &quot;7.9&quot;  &quot;6.3&quot;  &quot;2&quot;    &quot;1.6&quot;  &quot;0.4&quot;  &quot;3.2&quot;  &quot;3.9&quot;  &quot;4.5&quot;  &quot;6.1&quot;  &quot;10.9&quot;
##  [631] &quot;13.4&quot; &quot;11.4&quot; &quot;9.4&quot;  &quot;3.8&quot;  &quot;2.2&quot;  &quot;2.2&quot;  &quot;3.1&quot;  &quot;0.7&quot;  &quot;2.1&quot;  &quot;2.1&quot; 
##  [641] &quot;7.2&quot;  &quot;9.3&quot;  &quot;11.6&quot; &quot;12.6&quot; &quot;9.4&quot;  &quot;8.3&quot;  &quot;4.7&quot;  &quot;0.6&quot;  &quot;1.1&quot;  &quot;0.3&quot; 
##  [651] &quot;1.8&quot;  &quot;4.1&quot;  &quot;7.3&quot;  &quot;9.5&quot;  &quot;10.4&quot; &quot;11&quot;   &quot;9&quot;    &quot;7&quot;    &quot;4.2&quot;  &quot;3&quot;   
##  [661] &quot;-0.4&quot; &quot;2.7&quot;  &quot;1.5&quot;  &quot;2.4&quot;  &quot;9&quot;    &quot;9.8&quot;  &quot;12.2&quot; &quot;10.7&quot; &quot;9.4&quot;  &quot;8.1&quot; 
##  [671] &quot;5&quot;    &quot;1.6&quot;  &quot;1.1&quot;  &quot;-0.6&quot; &quot;1.2&quot;  &quot;3.5&quot;  &quot;5.4&quot;  &quot;8.8&quot;  &quot;11.7&quot; &quot;11.7&quot;
##  [681] &quot;9.1&quot;  &quot;8.1&quot;  &quot;2.3&quot;  &quot;1.9&quot;  &quot;1.6&quot;  &quot;2.8&quot;  &quot;1.9&quot;  &quot;4.2&quot;  &quot;7.3&quot;  &quot;11.3&quot;
##  [691] &quot;11.1&quot; &quot;12&quot;   &quot;9.1&quot;  &quot;8.5&quot;  &quot;0.4&quot;  &quot;4.7&quot;  &quot;1.3&quot;  &quot;2.4&quot;  &quot;2.7&quot;  &quot;4.2&quot; 
##  [701] &quot;8.4&quot;  &quot;10.5&quot; &quot;13.1&quot; &quot;14&quot;   &quot;9.4&quot;  &quot;6.7&quot;  &quot;3.6&quot;  &quot;4.6&quot;  &quot;1.7&quot;  &quot;3.7&quot; 
##  [711] &quot;5&quot;    &quot;3.8&quot;  &quot;8.8&quot;  &quot;10.2&quot; &quot;12.5&quot; &quot;10&quot;   &quot;7.7&quot;  &quot;3.9&quot;  &quot;4.1&quot;  &quot;5&quot;   
##  [721] &quot;3&quot;    &quot;1.9&quot;  &quot;3.3&quot;  &quot;4.7&quot;  &quot;7.8&quot;  &quot;10&quot;   &quot;11.4&quot; &quot;11.1&quot; &quot;10.8&quot; &quot;8.5&quot; 
##  [731] &quot;5.7&quot;  &quot;2.8&quot;  &quot;1.2&quot;  &quot;3.8&quot;  &quot;3.3&quot;  &quot;4.7&quot;  &quot;6.4&quot;  &quot;10&quot;   &quot;12.2&quot; &quot;12.1&quot;
##  [741] &quot;8.3&quot;  &quot;7.2&quot;  &quot;4&quot;    &quot;2.6&quot;  &quot;2.2&quot;  &quot;1.9&quot;  &quot;1.8&quot;  &quot;3.5&quot;  &quot;6.4&quot;  &quot;9.5&quot; 
##  [751] &quot;11.3&quot; &quot;12.2&quot; &quot;8.6&quot;  &quot;6.3&quot;  &quot;0.1&quot;  &quot;3.5&quot;  &quot;5.1&quot;  &quot;1.1&quot;  &quot;1.1&quot;  &quot;4.3&quot; 
##  [761] &quot;7.6&quot;  &quot;8.1&quot;  &quot;11&quot;   &quot;12.6&quot; &quot;9&quot;    &quot;8.2&quot;  &quot;3.8&quot;  &quot;-0.6&quot; &quot;0.1&quot;  &quot;-1.4&quot;
##  [771] &quot;0&quot;    &quot;1.8&quot;  &quot;8.2&quot;  &quot;10.8&quot; &quot;11.9&quot; &quot;12.7&quot; &quot;10.8&quot; &quot;4&quot;    &quot;5.3&quot;  &quot;-0.7&quot;
##  [781] &quot;1.3&quot;  &quot;3.9&quot;  &quot;2.1&quot;  &quot;3.6&quot;  &quot;8&quot;    &quot;8.5&quot;  &quot;11.7&quot; &quot;12&quot;   &quot;9&quot;    &quot;6.4&quot; 
##  [791] &quot;2.1&quot;  &quot;5&quot;    &quot;0.6&quot;  &quot;-1&quot;   &quot;1&quot;    &quot;3.3&quot;  &quot;7.8&quot;  &quot;9.7&quot;  &quot;10.2&quot; &quot;12&quot;  
##  [801] &quot;8.7&quot;  &quot;2.3&quot;  &quot;1&quot;    &quot;3.2&quot;  &quot;2.8&quot;  &quot;2.7&quot;  &quot;3.8&quot;  &quot;5.9&quot;  &quot;7.8&quot;  &quot;10.1&quot;
##  [811] &quot;11&quot;   &quot;9.7&quot;  &quot;9.3&quot;  &quot;6.6&quot;  &quot;3.4&quot;  &quot;2.2&quot;  &quot;5.2&quot;  &quot;1.4&quot;  &quot;4.1&quot;  &quot;3.9&quot; 
##  [821] &quot;6.9&quot;  &quot;9.5&quot;  &quot;13.3&quot; &quot;12.1&quot; &quot;9.3&quot;  &quot;8.2&quot;  &quot;1.7&quot;  &quot;3.6&quot;  &quot;1.3&quot;  &quot;1.4&quot; 
##  [831] &quot;1.8&quot;  &quot;1.9&quot;  &quot;8.1&quot;  &quot;9.3&quot;  &quot;10.4&quot; &quot;10.1&quot; &quot;8.8&quot;  &quot;4&quot;    &quot;2.3&quot;  &quot;3.9&quot; 
##  [841] &quot;2.2&quot;  &quot;3.7&quot;  &quot;3.6&quot;  &quot;4.3&quot;  &quot;6&quot;    &quot;8.8&quot;  &quot;13.5&quot; &quot;11.1&quot; &quot;8.5&quot;  &quot;7.1&quot; 
##  [851] &quot;0&quot;    &quot;1&quot;    &quot;3&quot;    &quot;0.4&quot;  &quot;-0.2&quot; &quot;3.7&quot;  &quot;8&quot;    &quot;10.4&quot; &quot;10.9&quot; &quot;10.5&quot;
##  [861] &quot;10.5&quot; &quot;7.3&quot;  &quot;4.8&quot;  &quot;4.3&quot;  &quot;2.3&quot;  &quot;2.5&quot;  &quot;1.5&quot;  &quot;3.6&quot;  &quot;7.8&quot;  &quot;9.9&quot; 
##  [871] &quot;12.3&quot; &quot;12&quot;   &quot;7.8&quot;  &quot;6.9&quot;  &quot;1.4&quot;  &quot;0.4&quot;  &quot;1.5&quot;  &quot;4.7&quot;  &quot;3.3&quot;  &quot;5.2&quot; 
##  [881] &quot;6.6&quot;  &quot;9.4&quot;  &quot;12.9&quot; &quot;12.1&quot; &quot;11&quot;   &quot;4.5&quot;  &quot;3.6&quot;  &quot;1.3&quot;  &quot;1.8&quot;  &quot;1.3&quot; 
##  [891] &quot;4.4&quot;  &quot;4.5&quot;  &quot;6.8&quot;  &quot;8.8&quot;  &quot;12.6&quot; &quot;12.2&quot; &quot;9.6&quot;  &quot;6.8&quot;  &quot;3.5&quot;  &quot;0.3&quot; 
##  [901] &quot;2.2&quot;  &quot;2.2&quot;  &quot;3.4&quot;  &quot;4.5&quot;  &quot;6.4&quot;  &quot;9.1&quot;  &quot;12.4&quot; &quot;11.7&quot; &quot;7.9&quot;  &quot;6.8&quot; 
##  [911] &quot;4.6&quot;  &quot;0.4&quot;  &quot;-1.1&quot; &quot;-3&quot;   &quot;-0.1&quot; &quot;2.5&quot;  &quot;6.4&quot;  &quot;8.9&quot;  &quot;11.2&quot; &quot;11.6&quot;
##  [921] &quot;10.7&quot; &quot;6.3&quot;  &quot;3.3&quot;  &quot;3.4&quot;  &quot;3.4&quot;  &quot;0.3&quot;  &quot;1.8&quot;  &quot;5&quot;    &quot;7&quot;    &quot;10.8&quot;
##  [931] &quot;11.7&quot; &quot;12&quot;   &quot;10.5&quot; &quot;7.5&quot;  &quot;2.8&quot;  &quot;1.9&quot;  &quot;0.8&quot;  &quot;1.3&quot;  &quot;0.3&quot;  &quot;4.7&quot; 
##  [941] &quot;7.8&quot;  &quot;11&quot;   &quot;12.1&quot; &quot;11.2&quot; &quot;8.3&quot;  &quot;5.2&quot;  &quot;5.1&quot;  &quot;2.8&quot;  &quot;3.5&quot;  &quot;-0.4&quot;
##  [951] &quot;0.4&quot;  &quot;3.8&quot;  &quot;7.5&quot;  &quot;9.5&quot;  &quot;12.7&quot; &quot;13.6&quot; &quot;9.7&quot;  &quot;5.9&quot;  &quot;4&quot;    &quot;3.5&quot; 
##  [961] &quot;-0.7&quot; &quot;1.4&quot;  &quot;3.3&quot;  &quot;4.5&quot;  &quot;8.1&quot;  &quot;10.6&quot; &quot;13.6&quot; &quot;12.7&quot; &quot;10.7&quot; &quot;6.7&quot; 
##  [971] &quot;2.8&quot;  &quot;-0.7&quot; &quot;0.6&quot;  &quot;-0.5&quot; &quot;1.3&quot;  &quot;4.5&quot;  &quot;6.9&quot;  &quot;10.6&quot; &quot;12.9&quot; &quot;11.4&quot;
##  [981] &quot;10.7&quot; &quot;7.6&quot;  &quot;3.9&quot;  &quot;5.9&quot;  &quot;2.5&quot;  &quot;2.9&quot;  &quot;2.8&quot;  &quot;4.4&quot;  &quot;5.4&quot;  &quot;11.2&quot;
##  [991] &quot;12.7&quot; &quot;12.1&quot; &quot;10.2&quot; &quot;6.1&quot;  &quot;4.3&quot;  &quot;0.9&quot;  &quot;1.7&quot;  &quot;-0.3&quot; &quot;4.1&quot;  &quot;2.9&quot; 
## [1001] &quot;6.8&quot;  &quot;10.6&quot; &quot;12&quot;   &quot;11.7&quot; &quot;11.3&quot; &quot;5.2&quot;  &quot;2.2&quot;  &quot;2.2&quot;  &quot;2.5&quot;  &quot;3.5&quot; 
## [1011] &quot;0.8&quot;  &quot;5.8&quot;  &quot;8.2&quot;  &quot;10&quot;   &quot;12.6&quot; &quot;12.5&quot; &quot;9.1&quot;  &quot;7.2&quot;  &quot;1.6&quot;  &quot;0.7&quot; 
## [1021] &quot;3.4&quot;  &quot;2&quot;    &quot;4.3&quot;  &quot;2.5&quot;  &quot;6.5&quot;  &quot;10.8&quot; &quot;11.7&quot; &quot;12.6&quot; &quot;10.1&quot; &quot;7.1&quot; 
## [1031] &quot;6.9&quot;  &quot;1.5&quot;  &quot;2.3&quot;  &quot;2.8&quot;  &quot;2.8&quot;  &quot;4.9&quot;  &quot;7.3&quot;  &quot;9.7&quot;  &quot;12.1&quot; &quot;12.4&quot;
## [1041] &quot;10.8&quot; &quot;5.2&quot;  &quot;6.5&quot;  &quot;0.6&quot;  &quot;-4.6&quot; &quot;0.2&quot;  &quot;2.5&quot;  &quot;5&quot;    &quot;7.8&quot;  &quot;11.1&quot;
## [1051] &quot;11.1&quot; &quot;11.1&quot; &quot;8.6&quot;  &quot;6&quot;    &quot;4.3&quot;  &quot;0.8&quot;  &quot;-1.2&quot; &quot;1.3&quot;  &quot;1.4&quot;  &quot;3.1&quot; 
## [1061] &quot;5&quot;    &quot;10.9&quot; &quot;13.1&quot; &quot;11.3&quot; &quot;10.4&quot; &quot;6.4&quot;  &quot;4.2&quot;  &quot;2.7&quot;  &quot;-2&quot;   &quot;-2.6&quot;
## [1071] &quot;1.9&quot;  &quot;5.1&quot;  &quot;6.8&quot;  &quot;9.5&quot;  &quot;11.8&quot; &quot;12.8&quot; &quot;10&quot;   &quot;7.3&quot;  &quot;1.9&quot;  &quot;4.7&quot; 
## [1081] &quot;2.9&quot;  &quot;2.7&quot;  &quot;2.2&quot;  &quot;6.9&quot;  &quot;7.7&quot;  &quot;10.3&quot; &quot;11.9&quot; &quot;12.4&quot; &quot;9.2&quot;  &quot;6.8&quot; 
## [1091] &quot;3.1&quot;  &quot;0.7&quot;  &quot;3&quot;    &quot;0.9&quot;  &quot;1.2&quot;  &quot;6.1&quot;  &quot;6.5&quot;  &quot;9.6&quot;  &quot;13.1&quot; &quot;13&quot;  
## [1101] &quot;8.6&quot;  &quot;6.6&quot;  &quot;3.6&quot;  &quot;0.8&quot;  &quot;-2&quot;   &quot;4.7&quot;  &quot;3.9&quot;  &quot;5.6&quot;  &quot;8.2&quot;  &quot;10.8&quot;
## [1111] &quot;12.8&quot; &quot;11.7&quot; &quot;11.5&quot; &quot;8&quot;    &quot;4.4&quot;  &quot;2.5&quot;  &quot;0.1&quot;  &quot;4&quot;    &quot;1.3&quot;  &quot;5&quot;   
## [1121] &quot;6.2&quot;  &quot;9.5&quot;  &quot;12.7&quot; &quot;11.4&quot; &quot;11&quot;   &quot;7.1&quot;  &quot;5.7&quot;  &quot;-0.1&quot; &quot;-0.6&quot; &quot;-4.4&quot;
## [1131] &quot;1.3&quot;  &quot;5.2&quot;  &quot;9&quot;    &quot;11.4&quot; &quot;13.6&quot; &quot;13.1&quot; &quot;11.1&quot; &quot;5.6&quot;  &quot;4.6&quot;  &quot;2.8&quot; 
## [1141] &quot;3.2&quot;  &quot;2.2&quot;  &quot;3.5&quot;  &quot;4.4&quot;  &quot;6.5&quot;  &quot;9.9&quot;  &quot;12.1&quot; &quot;11.9&quot; &quot;10.7&quot; &quot;6.4&quot; 
## [1151] &quot;4.2&quot;  &quot;3.4&quot;  &quot;3.1&quot;  &quot;1.6&quot;  &quot;1.7&quot;  &quot;6.1&quot;  &quot;6.6&quot;  &quot;10.3&quot; &quot;12.8&quot; &quot;12.6&quot;
## [1161] &quot;12.5&quot; &quot;8.4&quot;  &quot;3.4&quot;  &quot;3.3&quot;  &quot;1.5&quot;  &quot;2.8&quot;  &quot;3.6&quot;  &quot;4.2&quot;  &quot;7.1&quot;  &quot;11.8&quot;
## [1171] &quot;12.5&quot; &quot;12.2&quot; &quot;10&quot;   &quot;6.6&quot;  &quot;4&quot;    &quot;-0.7&quot; &quot;2&quot;    &quot;1.4&quot;  &quot;1.6&quot;  &quot;2.9&quot; 
## [1181] &quot;6.5&quot;  &quot;9.4&quot;  &quot;12.1&quot; &quot;11.7&quot; &quot;10.7&quot; &quot;5&quot;    &quot;6.2&quot;  &quot;3&quot;    &quot;0.3&quot;  &quot;0.3&quot; 
## [1191] &quot;3.9&quot;  &quot;5.4&quot;  &quot;9.5&quot;  &quot;10.5&quot; &quot;12.9&quot; &quot;12.6&quot; &quot;7.2&quot;  &quot;5.6&quot;  &quot;1.3&quot;  &quot;-0.6&quot;
## [1201] &quot;0.8&quot;  &quot;1.1&quot;  &quot;0.3&quot;  &quot;3.5&quot;  &quot;8.2&quot;  &quot;10.5&quot; &quot;11.7&quot; &quot;12.2&quot; &quot;10&quot;   &quot;6.5&quot; 
## [1211] &quot;5.9&quot;  &quot;5&quot;    &quot;0.3&quot;  &quot;0.2&quot;  &quot;2.9&quot;  &quot;2.8&quot;  &quot;7.2&quot;  &quot;10.3&quot; &quot;11.3&quot; &quot;11.3&quot;
## [1221] &quot;9.4&quot;  &quot;9.3&quot;  &quot;3.8&quot;  &quot;4.4&quot;  &quot;0.3&quot;  &quot;-1.1&quot; &quot;-0.4&quot; &quot;5.6&quot;  &quot;6&quot;    &quot;10.1&quot;
## [1231] &quot;12.6&quot; &quot;13.6&quot; &quot;10&quot;   &quot;5.4&quot;  &quot;3.7&quot;  &quot;2.2&quot;  &quot;1&quot;    &quot;-3.5&quot; &quot;2.2&quot;  &quot;2.6&quot; 
## [1241] &quot;7.1&quot;  &quot;9.6&quot;  &quot;12.5&quot; &quot;10.6&quot; &quot;11.1&quot; &quot;5.8&quot;  &quot;2.9&quot;  &quot;3.5&quot;  &quot;3&quot;    &quot;3.2&quot; 
## [1251] &quot;5.9&quot;  &quot;5.1&quot;  &quot;6.2&quot;  &quot;10.1&quot; &quot;13.4&quot; &quot;12.1&quot; &quot;9.7&quot;  &quot;7.6&quot;  &quot;3.7&quot;  &quot;1.6&quot; 
## [1261] &quot;1&quot;    &quot;2.3&quot;  &quot;0.9&quot;  &quot;3.6&quot;  &quot;7.9&quot;  &quot;10.7&quot; &quot;12.3&quot; &quot;12.7&quot; &quot;11.8&quot; &quot;8.1&quot; 
## [1271] &quot;4.2&quot;  &quot;2.7&quot;  &quot;-0.6&quot; &quot;1.3&quot;  &quot;4.1&quot;  &quot;6.3&quot;  &quot;7.7&quot;  &quot;10.9&quot; &quot;12.8&quot; &quot;13&quot;  
## [1281] &quot;9.4&quot;  &quot;7.8&quot;  &quot;3.7&quot;  &quot;3.4&quot;  &quot;1.6&quot;  &quot;1.9&quot;  &quot;3.9&quot;  &quot;4.8&quot;  &quot;8.8&quot;  &quot;11.9&quot;
## [1291] &quot;11.9&quot; &quot;11.4&quot; &quot;9.8&quot;  &quot;7.9&quot;  &quot;4.7&quot;  &quot;2.2&quot;  &quot;1.8&quot;  &quot;4.9&quot;  &quot;3.7&quot;  &quot;7&quot;   
## [1301] &quot;7.2&quot;  &quot;10.2&quot; &quot;11.9&quot; &quot;12&quot;   &quot;11.5&quot; &quot;7.5&quot;  &quot;3.1&quot;  &quot;-0.3&quot; &quot;1.6&quot;  &quot;1.6&quot; 
## [1311] &quot;-0.7&quot; &quot;4.5&quot;  &quot;7&quot;    &quot;9.3&quot;  &quot;11.8&quot; &quot;11.6&quot; &quot;9.5&quot;  &quot;6.8&quot;  &quot;2.8&quot;  &quot;-1.6&quot;
## [1321] &quot;-5.8&quot; &quot;-3.1&quot; &quot;3.1&quot;  &quot;5.7&quot;  &quot;6.9&quot;  &quot;11&quot;   &quot;11.4&quot; &quot;11.2&quot; &quot;9.7&quot;  &quot;8.4&quot; 
## [1331] &quot;6.3&quot;  &quot;0&quot;    &quot;1.1&quot;  &quot;2.5&quot;  &quot;2.1&quot;  &quot;5.6&quot;  &quot;9.3&quot;  &quot;10.7&quot; &quot;12.7&quot; &quot;11.8&quot;
## [1341] &quot;9.6&quot;  &quot;4.9&quot;  &quot;5&quot;    &quot;0.7&quot;  &quot;1.2&quot;  &quot;0.5&quot;  &quot;1.8&quot;  &quot;4.5&quot;  &quot;8.4&quot;  &quot;10.8&quot;
## [1351] &quot;11&quot;   &quot;11&quot;   &quot;9.1&quot;  &quot;7&quot;    &quot;1.9&quot;  &quot;2.4&quot;  &quot;0.8&quot;  &quot;4.6&quot;  &quot;3.2&quot;  &quot;5&quot;   
## [1361] &quot;7.2&quot;  &quot;11.3&quot; &quot;11.7&quot; &quot;11.1&quot; &quot;10.3&quot; &quot;7.9&quot;  &quot;2.9&quot;  &quot;3&quot;    &quot;2.6&quot;  &quot;2.9&quot; 
## [1371] &quot;4.2&quot;  &quot;4.7&quot;  &quot;7.5&quot;  &quot;9.9&quot;  &quot;13.1&quot; &quot;12.3&quot; &quot;10.9&quot; &quot;8.8&quot;  &quot;3&quot;    &quot;2&quot;   
## [1381] &quot;2&quot;    &quot;-0.1&quot; &quot;3.6&quot;  &quot;4.4&quot;  &quot;6.7&quot;  &quot;11.4&quot; &quot;12&quot;   &quot;12.3&quot; &quot;11.1&quot; &quot;10.6&quot;
## [1391] &quot;4.6&quot;  &quot;1.1&quot;  &quot;3.6&quot;  &quot;-0.9&quot; &quot;1.1&quot;  &quot;3.7&quot;  &quot;8.3&quot;  &quot;9.5&quot;  &quot;13.1&quot; &quot;13.2&quot;
## [1401] &quot;10.8&quot; &quot;9.9&quot;  &quot;3.2&quot;  &quot;1.2&quot;  &quot;1.9&quot;  &quot;0.6&quot;  &quot;0.6&quot;  &quot;3.8&quot;  &quot;8.7&quot;  &quot;11.6&quot;
## [1411] &quot;11.9&quot; &quot;12.2&quot; &quot;11.2&quot; &quot;7.4&quot;  &quot;5.6&quot;  &quot;1.8&quot;  &quot;2.5&quot;  &quot;1.5&quot;  &quot;2.2&quot;  &quot;4.3&quot; 
## [1421] &quot;7.4&quot;  &quot;9.4&quot;  &quot;13.1&quot; &quot;12.7&quot; &quot;9.8&quot;  &quot;7.4&quot;  &quot;3&quot;    &quot;4.6&quot;  &quot;2&quot;    &quot;2.5&quot; 
## [1431] &quot;2.8&quot;  &quot;5.4&quot;  &quot;7.4&quot;  &quot;8.8&quot;  &quot;11.8&quot; &quot;11.6&quot; &quot;8.3&quot;  &quot;7.4&quot;  &quot;3.8&quot;  &quot;3.5&quot; 
## [1441] &quot;2.1&quot;  &quot;1.3&quot;  &quot;2.1&quot;  &quot;4.2&quot;  &quot;8.1&quot;  &quot;10.9&quot; &quot;12.2&quot; &quot;12.8&quot; &quot;11&quot;   &quot;5.5&quot; 
## [1451] &quot;3.2&quot;  &quot;2.3&quot;  &quot;3.6&quot;  &quot;3.1&quot;  &quot;2.4&quot;  &quot;3.8&quot;  &quot;6.8&quot;  &quot;10.1&quot; &quot;12.2&quot; &quot;11.3&quot;
## [1461] &quot;9.1&quot;  &quot;4.9&quot;  &quot;5&quot;    &quot;5.9&quot;  &quot;4.6&quot;  &quot;1.8&quot;  &quot;2.5&quot;  &quot;5.3&quot;  &quot;6.4&quot;  &quot;9.4&quot; 
## [1471] &quot;13.4&quot; &quot;14.1&quot; &quot;9.9&quot;  &quot;6.5&quot;  &quot;2.5&quot;  &quot;1.7&quot;  &quot;3.4&quot;  &quot;2.3&quot;  &quot;1.7&quot;  &quot;4.1&quot; 
## [1481] &quot;8.3&quot;  &quot;12.6&quot; &quot;13.2&quot; &quot;11.4&quot; &quot;10.5&quot; &quot;8.3&quot;  &quot;3.4&quot;  &quot;-0.4&quot; &quot;0.7&quot;  &quot;3.3&quot; 
## [1491] &quot;4.3&quot;  &quot;3.8&quot;  &quot;6.1&quot;  &quot;8.5&quot;  &quot;12&quot;   &quot;12.2&quot; &quot;10.4&quot; &quot;8.3&quot;  &quot;3.8&quot;  &quot;3.9&quot; 
## [1501] &quot;0.7&quot;  &quot;0.4&quot;  &quot;3.3&quot;  &quot;3.3&quot;  &quot;7.1&quot;  &quot;9.6&quot;  &quot;11.5&quot; &quot;11.4&quot; &quot;10.6&quot; &quot;8.1&quot; 
## [1511] &quot;5.5&quot;  &quot;2.2&quot;  &quot;-3.1&quot; &quot;-0.9&quot; &quot;2.1&quot;  &quot;4.8&quot;  &quot;6.8&quot;  &quot;10.7&quot; &quot;13&quot;   &quot;11.7&quot;
## [1521] &quot;9.6&quot;  &quot;8&quot;    &quot;3.9&quot;  &quot;3.8&quot;  &quot;-0.3&quot; &quot;3.2&quot;  &quot;2.3&quot;  &quot;4.9&quot;  &quot;6.3&quot;  &quot;10.7&quot;
## [1531] &quot;11.2&quot; &quot;12.8&quot; &quot;12.2&quot; &quot;6&quot;    &quot;4.4&quot;  &quot;2.9&quot;  &quot;2.4&quot;  &quot;0.2&quot;  &quot;6.4&quot;  &quot;4.4&quot; 
## [1541] &quot;8.2&quot;  &quot;10.4&quot; &quot;12.3&quot; &quot;12.7&quot; &quot;11&quot;   &quot;5.7&quot;  &quot;4.9&quot;  &quot;-2&quot;   &quot;-0.1&quot; &quot;2.7&quot; 
## [1551] &quot;2.9&quot;  &quot;4.9&quot;  &quot;7.2&quot;  &quot;12.7&quot; &quot;12.8&quot; &quot;12.9&quot; &quot;10.6&quot; &quot;7.8&quot;  &quot;6.1&quot;  &quot;1.9&quot; 
## [1561] &quot;4.7&quot;  &quot;-0.7&quot; &quot;3.3&quot;  &quot;3.7&quot;  &quot;7.8&quot;  &quot;11&quot;   &quot;15.4&quot; &quot;13.3&quot; &quot;11.1&quot; &quot;7.7&quot; 
## [1571] &quot;5.2&quot;  &quot;3.2&quot;  &quot;1.5&quot;  &quot;1&quot;    &quot;2.4&quot;  &quot;3.4&quot;  &quot;6&quot;    &quot;10.8&quot; &quot;12.2&quot; &quot;13.6&quot;
## [1581] &quot;11.2&quot; &quot;8.6&quot;  &quot;6&quot;    &quot;2.7&quot;  &quot;-1.9&quot; &quot;-0.8&quot; &quot;1.4&quot;  &quot;5.1&quot;  &quot;7.3&quot;  &quot;9&quot;   
## [1591] &quot;12.7&quot; &quot;12.1&quot; &quot;11.2&quot; &quot;7.9&quot;  &quot;1.7&quot;  &quot;5.1&quot;  &quot;1.1&quot;  &quot;-4.1&quot; &quot;2.1&quot;  &quot;3.1&quot; 
## [1601] &quot;8&quot;    &quot;10.5&quot; &quot;12.8&quot; &quot;11&quot;   &quot;7.5&quot;  &quot;7.8&quot;  &quot;5.4&quot;  &quot;3.8&quot;  &quot;-1.4&quot; &quot;1&quot;   
## [1611] &quot;1.5&quot;  &quot;6.6&quot;  &quot;6.5&quot;  &quot;10.4&quot; &quot;12.7&quot; &quot;12.5&quot; &quot;10.9&quot; &quot;6.7&quot;  &quot;4.3&quot;  &quot;3.7&quot; 
## [1621] &quot;3.3&quot;  &quot;2.3&quot;  &quot;3.8&quot;  &quot;4.6&quot;  &quot;7.8&quot;  &quot;10.3&quot; &quot;11.6&quot; &quot;11.9&quot; &quot;10.4&quot; &quot;8&quot;   
## [1631] &quot;1.6&quot;  &quot;5.4&quot;  &quot;3.6&quot;  &quot;3&quot;    &quot;4.6&quot;  &quot;3.6&quot;  &quot;8.6&quot;  &quot;10.5&quot; &quot;14&quot;   &quot;12.4&quot;
## [1641] &quot;11.9&quot; &quot;8.9&quot;  &quot;3.2&quot;  &quot;3.3&quot;  &quot;4.5&quot;  &quot;5.3&quot;  &quot;5&quot;    &quot;3.3&quot;  &quot;7.8&quot;  &quot;10.7&quot;
## [1651] &quot;12.2&quot; &quot;14&quot;   &quot;9.4&quot;  &quot;9.3&quot;  &quot;4.3&quot;  &quot;1.7&quot;  &quot;1.2&quot;  &quot;-1.6&quot; &quot;5.1&quot;  &quot;4.6&quot; 
## [1661] &quot;7.4&quot;  &quot;9&quot;    &quot;13.7&quot; &quot;13.3&quot; &quot;10.6&quot; &quot;7.3&quot;  &quot;4.5&quot;  &quot;1.6&quot;  &quot;1.5&quot;  &quot;2.1&quot; 
## [1671] &quot;4.8&quot;  &quot;5.6&quot;  &quot;9.1&quot;  &quot;11.7&quot; &quot;13.5&quot; &quot;12.8&quot; &quot;10.8&quot; &quot;5.2&quot;  &quot;4.7&quot;  &quot;1.3&quot; 
## [1681] &quot;3.5&quot;  &quot;2.4&quot;  &quot;3.9&quot;  &quot;6.6&quot;  &quot;8&quot;    &quot;11.5&quot; &quot;12.3&quot; &quot;11.1&quot; &quot;9.3&quot;  &quot;6&quot;   
## [1691] &quot;2.6&quot;  &quot;3.4&quot;  &quot;3.3&quot;  &quot;1.3&quot;  &quot;5.3&quot;  &quot;5.1&quot;  &quot;7.6&quot;  &quot;11&quot;   &quot;13.8&quot; &quot;13&quot;  
## [1701] &quot;10.4&quot; &quot;6.9&quot;  &quot;8.4&quot;  &quot;3.9&quot;  &quot;2.2&quot;  &quot;4.4&quot;  &quot;2&quot;    &quot;5.4&quot;  &quot;7.8&quot;  &quot;10.4&quot;
## [1711] &quot;13.9&quot; &quot;13.9&quot; &quot;10.3&quot; &quot;10.3&quot; &quot;5.2&quot;  &quot;0.2&quot;  &quot;3.1&quot;  &quot;-0.1&quot; &quot;1.8&quot;  &quot;4.8&quot; 
## [1721] &quot;5.6&quot;  &quot;10.2&quot; &quot;12.7&quot; &quot;12.5&quot; &quot;10.3&quot; &quot;8.6&quot;  &quot;2.9&quot;  &quot;0.9&quot;  &quot;-0.2&quot; &quot;4.2&quot; 
## [1731] &quot;5.5&quot;  &quot;4.9&quot;  &quot;7.4&quot;  &quot;11.3&quot; &quot;12.9&quot; &quot;15.7&quot; &quot;10.7&quot; &quot;6.6&quot;  &quot;6.1&quot;  &quot;3.6&quot; 
## [1741] &quot;2.9&quot;  &quot;4.1&quot;  &quot;5.4&quot;  &quot;5.1&quot;  &quot;9.1&quot;  &quot;11.5&quot; &quot;12.4&quot; &quot;11.9&quot; &quot;11.8&quot; &quot;8.2&quot; 
## [1751] &quot;2.2&quot;  &quot;3.2&quot;  &quot;3.4&quot;  &quot;2.9&quot;  &quot;4.8&quot;  &quot;6.1&quot;  &quot;9.7&quot;  &quot;10.1&quot; &quot;13.3&quot; &quot;12.9&quot;
## [1761] &quot;12.4&quot; &quot;7.1&quot;  &quot;5.3&quot;  &quot;1.7&quot;  &quot;2&quot;    &quot;3.8&quot;  &quot;4.2&quot;  &quot;4.8&quot;  &quot;8.6&quot;  &quot;12.2&quot;
## [1771] &quot;12.3&quot; &quot;13.3&quot; &quot;12.1&quot; &quot;8.2&quot;  &quot;4.8&quot;  &quot;4.2&quot;  &quot;1.2&quot;  &quot;2&quot;    &quot;3.1&quot;  &quot;4.8&quot; 
## [1781] &quot;7.9&quot;  &quot;10.6&quot; &quot;13.4&quot; &quot;12.9&quot; &quot;10.5&quot; &quot;11.1&quot; &quot;3.9&quot;  &quot;0.2&quot;  &quot;3.4&quot;  &quot;4.4&quot; 
## [1791] &quot;4.6&quot;  &quot;5.2&quot;  &quot;8.4&quot;  &quot;10.3&quot; &quot;12&quot;   &quot;12.9&quot; &quot;10&quot;   &quot;7.1&quot;  &quot;6.4&quot;  &quot;4.1&quot; 
## [1801] &quot;1.8&quot;  &quot;0.6&quot;  &quot;2.7&quot;  &quot;4.6&quot;  &quot;8.1&quot;  &quot;11.8&quot; &quot;13.4&quot; &quot;13.5&quot; &quot;8.1&quot;  &quot;3.9&quot; 
## [1811] &quot;5.7&quot;  &quot;1.8&quot;  &quot;2.7&quot;  &quot;2.9&quot;  &quot;3.4&quot;  &quot;6.2&quot;  &quot;8.6&quot;  &quot;12&quot;   &quot;12.2&quot; &quot;14.2&quot;
## [1821] &quot;11.7&quot; &quot;8.6&quot;  &quot;5.8&quot;  &quot;2.8&quot;  &quot;3.8&quot;  &quot;2.1&quot;  &quot;4.7&quot;  &quot;5.7&quot;  &quot;7.6&quot;  &quot;12&quot;  
## [1831] &quot;13.4&quot; &quot;12.2&quot; &quot;11.9&quot; &quot;10.9&quot; &quot;3.1&quot;  &quot;1.8&quot;  &quot;2.2&quot;  &quot;0.8&quot;  &quot;2&quot;    &quot;5.4&quot; 
## [1841] &quot;9&quot;    &quot;11.7&quot; &quot;14.9&quot; &quot;13.1&quot; &quot;13.5&quot; &quot;10.6&quot; &quot;5.1&quot;  &quot;4.3&quot;  &quot;4.8&quot;  &quot;3.7&quot; 
## [1851] &quot;3.7&quot;  &quot;5.6&quot;  &quot;7.1&quot;  &quot;11.3&quot; &quot;12.2&quot; &quot;12&quot;   &quot;10.3&quot; &quot;7.9&quot;  &quot;4.3&quot;  &quot;2.4&quot; 
## [1861] &quot;4.7&quot;  &quot;1.7&quot;  &quot;3.5&quot;  &quot;4.7&quot;  &quot;9.5&quot;  &quot;11.1&quot; &quot;12.8&quot; &quot;13.9&quot; &quot;10.2&quot; &quot;5.7&quot; 
## [1871] &quot;4.8&quot;  &quot;1.3&quot;  &quot;0.2&quot;  &quot;2&quot;    &quot;3.2&quot;  &quot;6.1&quot;  &quot;8.3&quot;  &quot;10.7&quot; &quot;13.1&quot; &quot;13.3&quot;
## [1881] &quot;10.6&quot; &quot;8.4&quot;  &quot;7&quot;    &quot;0.8&quot;  &quot;-1&quot;   &quot;1.3&quot;  &quot;3.2&quot;  &quot;4.9&quot;  &quot;7.3&quot;  &quot;11.1&quot;
## [1891] &quot;14.2&quot; &quot;12.1&quot; &quot;10.3&quot; &quot;7.4&quot;  &quot;2.9&quot;  &quot;-2.2&quot; &quot;1.9&quot;  &quot;4.4&quot;  &quot;3.2&quot;  &quot;7.3&quot; 
## [1901] &quot;8.4&quot;  &quot;10.2&quot; &quot;10.2&quot; &quot;11.4&quot; &quot;10.7&quot; &quot;9.5&quot;  &quot;6.3&quot;  &quot;3.1&quot;  &quot;3.6&quot;  &quot;1.2&quot; 
## [1911] &quot;3.6&quot;  &quot;4.6&quot;  &quot;9.7&quot;  &quot;11.6&quot; &quot;12.6&quot; &quot;13.6&quot; &quot;9.2&quot;  &quot;7.1&quot;  &quot;4.2&quot;  &quot;2.6&quot; 
## [1921] &quot;1.9&quot;  &quot;0.9&quot;  &quot;0.2&quot;  &quot;3.9&quot;  &quot;6.7&quot;  &quot;10.2&quot; &quot;13.9&quot; &quot;13.1&quot; &quot;9.9&quot;  &quot;9.9&quot; 
## [1931] &quot;3.8&quot;  &quot;3.6&quot;  &quot;3.5&quot;  &quot;4.2&quot;  &quot;3.5&quot;  &quot;6.4&quot;  &quot;8.9&quot;  &quot;11.8&quot; &quot;13.5&quot; &quot;11.7&quot;
## [1941] &quot;11.4&quot; &quot;9.9&quot;  &quot;5.7&quot;  &quot;2.4&quot;  &quot;1.6&quot;  &quot;1&quot;    &quot;3.3&quot;  &quot;4.5&quot;  &quot;7.7&quot;  &quot;10.2&quot;
## [1951] &quot;12.5&quot; &quot;13&quot;   &quot;8.9&quot;  &quot;7.9&quot;  &quot;7.3&quot;  &quot;8.3&quot;  &quot;3&quot;    &quot;2.7&quot;  &quot;2.2&quot;  &quot;4&quot;   
## [1961] &quot;8.7&quot;  &quot;11.9&quot; &quot;13.8&quot; &quot;13.6&quot; &quot;13&quot;   &quot;7.3&quot;  &quot;3.3&quot;  &quot;3&quot;    &quot;0.8&quot;  &quot;4&quot;   
## [1971] &quot;5.8&quot;  &quot;4.7&quot;  &quot;9.4&quot;  &quot;12.9&quot; &quot;13.9&quot; &quot;12.6&quot; &quot;10.4&quot; &quot;9.7&quot;  &quot;3.8&quot;  &quot;2.6&quot; 
## [1981] &quot;3&quot;    &quot;0.3&quot;  &quot;2.5&quot;  &quot;7.5&quot;  &quot;8.6&quot;  &quot;11.6&quot; &quot;14.2&quot; &quot;13.2&quot; &quot;10&quot;   &quot;7.3&quot; 
## [1991] &quot;5.5&quot;  &quot;4.7&quot;  &quot;1.3&quot;  &quot;2.4&quot;  &quot;5.2&quot;  &quot;4.3&quot;  &quot;7&quot;    &quot;11&quot;   &quot;13.9&quot; &quot;13.2&quot;
## [2001] &quot;10.4&quot; &quot;7.5&quot;  &quot;4.3&quot;  &quot;3.7&quot;  &quot;4.5&quot;  &quot;4.2&quot;  &quot;3&quot;    &quot;5.5&quot;  &quot;7.9&quot;  &quot;12.1&quot;
## [2011] &quot;13&quot;</code></pre>
<p>There is a missing value in this data. But rather unpleasantly it has been coded as “—”, which means the <code>tmin</code> column is being treated not as a number but as a string.</p>
<p>Thankfully there is an argument we can find within <code>read.csv</code> that allows for custom NA values. This also exists within the “Import Dataset” menu.</p>
<pre class="r"><code>oxford_data&lt;-read.csv(&quot;oxford_data.csv&quot;,na.strings = &quot;---&quot;)</code></pre>
<p>Again, we should double check to see if the data has been read in appropriately.</p>
<pre class="r"><code>summary(oxford_data)</code></pre>
<pre><code>##       yyyy            mm              tmax            tmin      
##  Min.   :1853   Min.   : 1.000   Min.   :-0.20   Min.   :-5.80  
##  1st Qu.:1894   1st Qu.: 3.000   1st Qu.: 9.00   1st Qu.: 2.80  
##  Median :1936   Median : 6.000   Median :13.80   Median : 5.60  
##  Mean   :1936   Mean   : 6.491   Mean   :13.95   Mean   : 6.22  
##  3rd Qu.:1978   3rd Qu.: 9.000   3rd Qu.:19.00   3rd Qu.:10.20  
##  Max.   :2020   Max.   :12.000   Max.   :27.40   Max.   :15.70  
##                                                  NA&#39;s   :1      
##       rain       
##  Min.   :  0.50  
##  1st Qu.: 31.45  
##  Median : 49.70  
##  Mean   : 54.70  
##  3rd Qu.: 74.75  
##  Max.   :192.90  
## </code></pre>
<p>And this time it looks better!</p>
</div>
<div id="section-stage-2-manipulate-data" class="section level2">
<h2>Stage 2: Manipulate Data</h2>
<p>Before going any further we should consider the structure of our data as it is now, and the structure of the data we need to be able to make a plot.</p>
<p>Right now the data we have is:</p>
<ul>
<li>One row per month<br />
</li>
<li>Two columns for temperature (tmax and tmin)</li>
</ul>
<p>The data we need for the plot would have:</p>
<ul>
<li>One row per year<br />
</li>
<li>One column for temperature anomaly</li>
</ul>
<p>So there are going to be quite a few steps needed here to get from A to B. We definitely want to try to work these out in advance before writing the code. Some people would find it useful to draw a diagram which might help think about what order the steps should be in.</p>
<p>There are broadly 5 steps needed. Some of these could be re-ordered and it would still be valid, but this is the order that made the most sense to me</p>
<p>2.1: Calculate a single monthly average temperature value - based on tmax and tmin values</p>
<p>2.2: Calculate the average temperature from within the reference period - this will be a single constant value</p>
<p>2.3: Grouping by year and then obtaining annual averages of the average temperatures</p>
<p>2.4: Calculate the temperature anomaly for each year</p>
<p>2.5: Remembering from what we found out in Stage 1 (Data Importing) - filtering to a sensible range of years with complete data</p>
<div id="section-calculate-a-single-monthly-average-temperature-value---based-on-tmax-and-tmin-values" class="section level3">
<h3>2.1 Calculate a single monthly average temperature value - based on tmax and tmin values</h3>
<p>To get the monthly average we will need to take the average of the tmax and tmin column. This is not a perfect method for obtaining average temperatures; see: <a href="https://journals.ametsoc.org/jamc/article/58/10/2235/343374/A-Significant-Bias-of-Tmax-and-Tmin-Average" class="uri">https://journals.ametsoc.org/jamc/article/58/10/2235/343374/A-Significant-Bias-of-Tmax-and-Tmin-Average</a> But it is the easiest and very commonly used given the availability of data.</p>
<p>We have seen many examples so far about how calculate average values from within a column from multiple rows. However in this case we need to taking an average of values from multiple <em>columns</em>.</p>
<p>This is a little trickier to do, the easiest way is to simply go back to first principles and remember the formula for calculating a mean - add all the values, then divide the sum by the number of values. I can do this using <code>mutate()</code> to create a new column called <code>tmean</code>.</p>
<pre class="r"><code>oxford_data&lt;-
  oxford_data %&gt;%
    mutate(tmean=(tmin+tmax)/2)</code></pre>
<p>I am also going to over-write the existing object at this point by assigning the output to be an object called <code>oxford_data</code>. Since step 2.2 will not be inside a continuous pipe (although in the video solution, I did use a slightly more complicated method to do everything within a single pipe. The code for that alternative is included at the end of this solution.)</p>
</div>
<div id="section-calculate-the-average-temperature-from-within-the-reference-period" class="section level3">
<h3>2.2: Calculate the average temperature from within the reference period</h3>
<p>From the updated data created in 2.1, I will filter to just the years 1971-2000 and then get the mean value.</p>
<pre class="r"><code>refmean=oxford_data %&gt;%
  filter(yyyy&gt;=1971 &amp; yyyy&lt;=2000) %&gt;%
    summarise(mean=mean(tmean))</code></pre>
</div>
<div id="section-grouping-by-year-and-then-obtaining-annual-averages-of-the-average-temperatures" class="section level3">
<h3>2.3: Grouping by year and then obtaining annual averages of the average temperatures</h3>
<p>Using <code>group_by</code> and <code>summarise</code> I can now calculate mean values for each year. Remember there was one missing value in our dataset. Because of the seasonality of temperature, if we use <code>na.rm=T</code> when calculating the mean temperature for the year, we will definitely have a biased estimate of the mean. Therefore it is probably safer to not use this option for calculating the mean, and leaving the mean for this year as an NA.</p>
<pre class="r"><code>oxford_data %&gt;%
  group_by(yyyy) %&gt;%
    summarise(tmean=mean(tmean))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 168 x 2
##     yyyy tmean
##    &lt;int&gt; &lt;dbl&gt;
##  1  1853  8.97
##  2  1854  9.69
##  3  1855  8.83
##  4  1856  9.53
##  5  1857 10.3 
##  6  1858  9.50
##  7  1859 10.1 
##  8  1860 NA   
##  9  1861  9.76
## 10  1862  9.90
## # ... with 158 more rows</code></pre>
</div>
<div id="section-calculate-the-temperature-anomaly-for-each-year" class="section level3">
<h3>2.4: Calculate the temperature anomaly for each year</h3>
<p>Finally we can calculate the temperature anomaly by subtracting the yearly averages from the 20th century average</p>
<pre class="r"><code>oxford_data %&gt;%
  group_by(yyyy) %&gt;%
    summarise(tmean=mean(tmean)) %&gt;%
        mutate(anomaly=tmean-refmean$mean)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 168 x 3
##     yyyy tmean anomaly
##    &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1  1853  8.97  -1.42 
##  2  1854  9.69  -0.699
##  3  1855  8.83  -1.56 
##  4  1856  9.53  -0.853
##  5  1857 10.3   -0.116
##  6  1858  9.50  -0.891
##  7  1859 10.1   -0.291
##  8  1860 NA     NA    
##  9  1861  9.76  -0.628
## 10  1862  9.90  -0.482
## # ... with 158 more rows</code></pre>
<p>Note that, even though there is only one value in the data frame <code>refmean</code> we still need to refer to the column name to access this value.</p>
</div>
<div id="section-filtering-to-a-sensible-range-of-years-with-complete-data" class="section level3">
<h3>2.5 Filtering to a sensible range of years with complete data</h3>
<p>Because of the missing value in 1860, then it probably makes sense to only plot the years we have complete data for. So let’s restrict the plot to only 1861 and onwards.</p>
<pre class="r"><code>oxford_plot_data&lt;-
  oxford_data %&gt;%
  group_by(yyyy) %&gt;%
    summarise(tmean=mean(tmean)) %&gt;%
        mutate(anomaly=tmean-refmean$mean)%&gt;%
          filter(yyyy&gt;=1861)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>Now that I have completed my data manipulation steps I also decide to assign this into a new object called <code>oxford_plot_data</code>.</p>
<p>We are now ready to make our plot!</p>
</div>
</div>
<div id="section-stage-3-plotting" class="section level2">
<h2>Stage 3: Plotting</h2>
<div id="section-make-the-initial-plot" class="section level3">
<h3>Make the initial plot</h3>
<p>Let’s deconstruct the plot structure to understand more how it works.</p>
<ul>
<li>We have year on the x axis<br />
</li>
<li>A coloured ‘stripe’ for each year, (a bar of constant height)<br />
</li>
<li>The colour represents the anomaly</li>
</ul>
<p>So within <code>ggplot2</code> our solution will be</p>
<ul>
<li>Map <code>yyyy</code> to the x axis<br />
</li>
<li>Map <code>anomaly</code> to the fill axis<br />
</li>
<li>The variable going onto the y axis should not be a variable at all! We want a constant, so we can just set this to be an arbitrary value. We do need to set this to be equal to some value, so R knows how high to make each bar<br />
</li>
<li>Use<code>geom_col</code> not <code>geom_bar</code>, because we are setting the heights of the bars, rather than using bars to summarise counts, or other statistics, from data</li>
</ul>
<p>This gives us:</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col()</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-11-1.png" width="624" /></p>
<p>Not a bad start!</p>
<p>Now we need to think about how to format this into the classic ‘warming bars’ style. There are a few things we need to do:</p>
<ol style="list-style-type: decimal">
<li>Change the colour palette so that low values are blue and high values are red and zero is white<br />
</li>
<li>Make the colour scale ‘symmetrical’. You can see from the legend that the zero value is not in the middle of scale.<br />
</li>
<li>Remove the small spaces between bars<br />
</li>
<li>Remove all the gridlines, axis labels, and backgrounds</li>
</ol>
</div>
<div id="section-colour-palette" class="section level3">
<h3>3.1 Colour Palette</h3>
<p>This is where we will need to use a <code>scale_</code> function, to modify the way the colours are allocated. There are a few different scale functions for creating colour gradients depending on whether you need a single colour gradient, a double colour gradient or a n-level colour gradient. In this particular case we need a double gradient - because we want to set negative values to go from dark blue up to white (at zero). Then from zero we want an additional gradient to go from white to dark red as numbers become more positive. So the function we need is <code>scale_fill_gradient2</code>. In this we need to set the colour values for our “low”, “mid” and “high” extremes of colour.</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col()+
    scale_fill_gradient2(low = &quot;darkblue&quot;,mid=&quot;white&quot;,high=&quot;darkred&quot;)</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-12-1.png" width="624" /></p>
<p>An alternative, and probably better, option is to use the new function <code>scale_fill_fermenter()</code>which works in a similar way to <code>scale_fill_brewer()</code> except with continuous variables being used to set colours instead. This is nice because the “RdBu” colour palette from colour brewer is exactly the colour palette used in the warming stripes plots.</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col()+
    scale_fill_fermenter(palette=&quot;RdBu&quot;)</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-13-1.png" width="624" /></p>
</div>
<div id="section-symmetrical-colour-scale" class="section level3">
<h3>3.2 Symmetrical colour scale</h3>
<p>A little suprisingly, because of the default options within <code>scale_fill_gradient2</code>, we now do have a symmetrical colour palette! The function defaults to a midpoint of zero, and stretches the colour assignments so that they are symmetrical. You can’t tell this from just looking at the plot, but the top level of ‘reds’ being plotted is not at the full extent of ‘darkred’ unlike the blue which does extend as far as possible. If we did want to make sure of this explicitly we could set the limits within the scale call, exactly as we might modify the limits of an x or y axis as we have seen previously.</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col()+
    scale_fill_gradient2(low = &quot;darkblue&quot;,mid=&quot;white&quot;,high=&quot;darkred&quot;,limits=c(-2,2))</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-14-1.png" width="624" /></p>
<p>The plot is identical, but you can see the darkest red in the legend is now a bit darker!</p>
<p>Within <code>scale_fill_fermenter</code> thought this is not automatic - so we would need to explicitly set limits.</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col()+
    scale_fill_fermenter(palette=&quot;RdBu&quot;,limits=c(-1.5,1.5))</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-15-1.png" width="624" /></p>
</div>
<div id="section-removing-spaces" class="section level3">
<h3>3.3 Removing spaces</h3>
<p>It may not be obvious without zooming in, but there are small spaces between each bar. This is because by default R sets bars to fill 95% of the width available, and leave 5% spacing between bars. However no such spaces exist in the ‘classic’ warming stripes. Thankfully this is easy to resolve by adding the option width=1 into geom_col.</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col(width=1)+
    scale_fill_fermenter(palette=&quot;RdBu&quot;,limits=c(-1.5,1.5))</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-16-1.png" width="624" /></p>
</div>
<div id="section-removing-labels-gridlines-etc." class="section level3">
<h3>3.4 Removing labels, gridlines etc.</h3>
<p>With the <code>theme()</code> function we can manually change individual components. We could use this to individually remove the labels, and gridlines. But there is also a built in theme which will do this for us - theme_void().</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col(width=1)+
    scale_fill_fermenter(palette=&quot;RdBu&quot;,limits=c(-1.5,1.5))+
    theme_void()</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-17-1.png" width="624" /></p>
<p>We might also want to get rid of the legend, and add a title. Just to add a finishing touch</p>
<pre class="r"><code>ggplot(data=oxford_plot_data,aes(x=yyyy,y=1,fill=anomaly))+
  geom_col(width=1,show.legend = FALSE)+
    scale_fill_fermenter(palette=&quot;RdBu&quot;,limits=c(-1.5,1.5))+
    theme_void()+
      labs(title=&quot;Oxford Warming Stripes&quot;,subtitle = &quot;1861-2019&quot;)</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-18-1.png" width="624" /></p>
<p>Job done!</p>
</div>
</div>
<div id="section-appendix-1-solution-in-one-pipe" class="section level2">
<h2>Appendix 1: Solution in one pipe</h2>
<p>For the very adventurous!</p>
<pre class="r"><code>oxford_data %&gt;%
  mutate(tave=(tmax+tmin)/2) %&gt;%
    group_by(yyyy) %&gt;%
      summarise(tave=mean(tave)) %&gt;%
        filter(yyyy&gt;1860) %&gt;%
          mutate(ref_temp=ifelse(yyyy&gt;=1971 &amp; yyyy &lt;=2000, tave,NA)) %&gt;%
            mutate(ref_ave=mean(ref_temp,na.rm=TRUE)) %&gt;%
              mutate(anomaly=tave-ref_ave) %&gt;%
                ggplot(aes(x=yyyy,fill=anomaly,y=1))+
                   geom_col(show.legend = FALSE,width=1)+
                     scale_fill_fermenter(palette=&quot;RdBu&quot;,limits=c(-1.5,1.5))+
                        theme_void()+
                           labs(fill=&quot;Temperature Anomaly&quot;,title=&quot;Oxford Warming Stripes&quot;,subtitle = &quot;1861-2019&quot;)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p><img src="warming-stripe-solution_files/figure-html/unnamed-chunk-19-1.png" width="624" /></p>
</div>
<div id="section-appendix-2-cleaning-the-data" class="section level2">
<h2>Appendix 2: Cleaning the data</h2>
<p>If you are interested in seeing how the raw data from the met office was tidied then you can watch this video.</p>
<p>[]<a href="https://youtu.be/6xG5U35pBFo" class="uri">https://youtu.be/6xG5U35pBFo</a></p>
The script created is saved here: <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.0"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","cli","colorspace","compiler","crayon","datasets","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","generics","ggplot2","glue","graphics","grDevices","grid","gtable","htmltools","htmlwidgets","httpuv","jsonlite","knitr","labeling","later","learnr","lifecycle","magrittr","markdown","methods","mime","munsell","pillar","pkgconfig","promises","purrr","R6","RColorBrewer","Rcpp","rlang","rmarkdown","rprojroot","scales","shiny","stats","stringi","stringr","tibble","tidyselect","tools","utf8","utils","vctrs","withr","xfun","xtable","yaml"]},{"type":"character","attributes":{},"value":["0.2.1","1.1.5","4.0.3","2.0.1","1.4-1","4.0.3","1.3.4","4.0.3","0.6.23","1.0.2","0.3.0","0.14","0.4.1","2.0.1","1.0.1","0.0.2","3.3.2","1.4.2","4.0.3","4.0.3","4.0.3","0.3.0","0.4.0","1.5.1","1.5.2","1.6.1","1.27","0.3","1.0.0","0.10.1","0.2.0","1.5","1.1","4.0.3","0.8","0.5.0","1.4.3","2.0.3","1.1.0","0.3.3","2.4.1","1.1-2","1.0.3","0.4.8","2.0","1.3-2","1.1.0","1.4.0","4.0.3","1.4.5","1.4.0","3.0.1","1.1.0","4.0.3","1.1.4","4.0.3","0.3.4","2.1.2","0.12","1.8-4","2.2.0"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Warming Stripes: A Problem solving task in R</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
